### PR TITLE
Alerts

### LINKED ISSUE #26: Add an error alert
Rather than just logging the error it should alert the user when something failed.

**This should be on any page that could result in an issue**

### PR DESCRIPTION
**Pull request by rsotoacu**
- Added alerts to login page 
- 2 different alerts are shown: in case there is a login fail due to network the alert says "Login fail" and in case of a 401 error the alert will ask the user to check credentials.

### CODE REVIEW

File: src/components/FailAlertMessage.js [hunk 1]
```diff
@@ -1,9 +1,8 @@
-// FailAlertMessage.js
 import React, { useEffect } from 'react';
 
 function FailAlertMessage({ message, visible, handleDismiss, timeout }) {
     useEffect(() => {
-        if (timeout) { // Allows the error to forever be displayed if timeout is not set
```
Comment (gtaEPIC) [inline src/components/FailAlertMessage.js]: Not sure why the comment was removed but ok

**Review by gtaEPIC — APPROVED** [review]
Looks and works good.
Preferably I wouldn't have removed the alert on the login page, but it doesn't really matter that much
